name: "Hello Actions"
description: "Greet someonse"
author: "changgeon718@github.com"

intputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

  runs:
    using: "docker"
    image: "Dockerfile"

  branding:
    icon: "mic"
    color: "purple"